services:
  web:
    build: .
    container_name: progetto
    ports:
      - "8080:80"
    volumes:
      - ./data:/var/www/html/data
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    restart: unless-stopped
